<template>
  <v-form ref="form" @submit.prevent="trySave">
    <v-divider thickness="4" color="black"></v-divider>
    <LinkItem :link="link" color="black" :use-native-icons="true" />
    <v-divider thickness="4" color="black"></v-divider>
    <slot name="content" />
    <TextField
      @input="(e) => updateLabel(e.target.value)"
      v-model="label"
      variant="underlined"
      label="Label (optional)"
      hint="This is optional, but it helps you remember what this link is for."
    />
    <p class="font-italic mt-4">Here are some suggestions for your label:</p>
    <div style="max-width: 400px">
      <v-row class="mt-1">
        <v-col v-for="suggestion in suggestionsMap[link.type]" cols="4">
          <v-btn
            max-width="130"
            min-width="100"
            class="elevation-0 text-capitalize"
            variant="outlined"
            rounded
            @click="updateLabel(suggestion)"
          >
            <p>{{ suggestion }}</p>
          </v-btn>
        </v-col>
      </v-row>
    </div>
    <v-divider thickness="3" class="mt-4"></v-divider>
    <v-row class="mt-3 mb-3">
      <v-col cols="6">
        <v-btn class="elevation-0 mr-3 text-capitalize" variant="outlined"
          >Cancel</v-btn
        >
        <v-btn class="bg-black elevation-0 text-capitalize" type="submit"
          >Save</v-btn
        >
      </v-col>
    </v-row>
  </v-form>
</template>

<script setup lang="ts">
import { LinkDTO } from "~~/api/dtos/card.dto";

const emit = defineEmits(["save"]);
const props = defineProps({
  link: {
    type: Object as PropType<LinkDTO>,
    required: true,
  },
  mode: {
    type: String as PropType<"edit" | "create">,
    required: true,
  },
});
const editor = useCardEditorStore();
const form = ref<HTMLFormElement | null>(null);
const label = ref("");

onMounted(() => {
  if (props.mode === "create") {
    editor.card.links.push({
      type: props.link.type,
      title: "",
      subtitle: "",
      id: "",
    });
  }
});

const updateLabel = (update: string) => {
  label.value = update.charAt(0).toUpperCase() + update.slice(1);
  if (props.mode === "create") {
    editor.card.links[editor.card.links.length - 1].subtitle = label.value;
  } else {
    editor.card.links.find((entry) => entry.id === props.link.id)!.subtitle =
      label.value;
  }
};
const onSave = () => {
  if (props.mode === "create") {
    // Add some sort of id here to make it easier to edit
    editor.card.links[editor.card.links.length - 1].id = generateId();
  }
  emit("save");
};
// Generate a unique id for the link
// This id is only valid for the current session that hans't been saved
// Most of the times this will not be needed, as the id is generated by the backend
const generateId = () => {
  return (
    props.link.type +
    ":" + 
    Math.random().toString(36) +
    ":" +
    label.value +
    ":" +
    props.link.title
  );
};
const trySave = async () => {
  if (!form.value) {
    return;
  }
  const { valid } = await form.value.validate();
  // Return if this is not a valid form
  if (!valid) {
    return;
  }
  onSave();
};

// Suggestions for the optional label
const suggestionsMap: { [key: string]: string[] } = {
  instagram: ["personal", "business", "entertainment", "news"],
  twitter: ["politics", "sports", "business", "personal"],
  tiktok: ["dance", "comedy", "education", "entertainment"],
  linkedin: ["professional", "networking", "recruiter"],
  facebook: ["personal", "family", "friends", "business"],
  email: ["personal", "work", "business", "newsletter"],
  phone: ["personal", "work", "business", "Emergency"],
  whatsapp: ["personal", "work", "group chat", "urgent"],
  discord: ["community", "gaming", "study group", "friends"],
  telegram: ["personal", "work", "group chat", "business"],
};
</script>
